spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haedal-practice
    username: root
    password: dbswodyd91
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always